# V1.0.0.3
name: KeefeCodes DevSecOps Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'

      - name: Install dependencies
        run: npm ci

      - name: Lint (code quality check)
        run: npm run lint --if-present || true
      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  security-scan:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate || true 

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [build-and-test, security-scan]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Setup SSH
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          ssh-add /tmp/deploy_key || (echo "SSH key failed to load. Check formatting in GitHub Secrets." && exit 1)

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REG_HOST }} >> ~/.ssh/known_hosts

      - name: Determine environment and deploy
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo "Deploying branch: $BRANCH"

          if [ "$BRANCH" == "dev" ]; then
            TARGET_DIR="/home/${{ secrets.REG_FTP_USERNAME }}/public_html/keefecodes.com/dev"
          elif [ "$BRANCH" == "main" ]; then
            TARGET_DIR="/home/${{ secrets.REG_FTP_USERNAME }}/public_html/keefecodes.com/live"
          else
            echo "Not a deployment branch."
            exit 0
          fi

          echo "Deploying build files to $TARGET_DIR ..."
          scp -r dist/* ${{ secrets.REG_FTP_USERNAME }}@${{ secrets.REG_HOST }}:$TARGET_DIR || (echo "❌ Deployment failed. Check server permissions or SSH key." && exit 1)

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()

    steps:
      - name: Send build/deploy status to Discord
        env:
          WEBHOOK_URL: ${{ secrets.KEEFECODES_DEVOPS_BOT }}
          STATUS: ${{ job.status }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          BRANCH: ${{ github.ref_name }}
        run: |
          if [ "$STATUS" == "success" ]; then
            COLOR=3066993
            STATUS_TEXT="✅ Deployment Succeeded"
          else
            COLOR=15158332
            STATUS_TEXT="❌ Deployment Failed"
          fi

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"username\": \"KeefeCodes CI/CD Bot\",
            \"embeds\": [{
              \"title\": \"$STATUS_TEXT\",
              \"color\": $COLOR,
              \"fields\": [
                {\"name\": \"Branch\", \"value\": \"$BRANCH\"},
                {\"name\": \"Commit Message\", \"value\": \"$COMMIT_MSG\"},
                {\"name\": \"Author\", \"value\": \"$COMMIT_AUTHOR\"}
              ],
              \"footer\": {\"text\": \"KeefeCodes DevSecOps Pipeline • $(date)\"}
            }]
          }" $WEBHOOK_URL